/**
 * A curated subset of Material Symbols icon names (Google Fonts).
 *
 * The full set has several thousand icons; Google does not publish a static
 * list this app can fetch offline, so this is a hand-picked catalogue of the
 * ones people reach for most, grouped for the search/browse UI in
 * `IconsPanel`. Each string is the icon's ligature name - the exact text the
 * font renders as that glyph - so it doubles as the element's text content.
 */

export interface MaterialSymbolGroup {
  label: string;
  icons: string[];
}

export const MATERIAL_SYMBOL_GROUPS: MaterialSymbolGroup[] = [
  {
    label: 'Nawigacja i strzałki',
    icons: [
      'home',
      'menu',
      'close',
      'arrow_back',
      'arrow_forward',
      'arrow_upward',
      'arrow_downward',
      'chevron_left',
      'chevron_right',
      'expand_more',
      'expand_less',
      'north',
      'south',
      'east',
      'west',
      'first_page',
      'last_page',
      'unfold_more',
      'unfold_less',
      'more_vert',
      'more_horiz',
      'apps',
      'dashboard',
      'map',
      'navigation',
      'my_location',
      'location_on',
      'explore',
      'compass_calibration',
    ],
  },
  {
    label: 'Akcje i interfejs',
    icons: [
      'search',
      'add',
      'remove',
      'edit',
      'delete',
      'check',
      'check_circle',
      'cancel',
      'settings',
      'tune',
      'filter_list',
      'sort',
      'refresh',
      'sync',
      'download',
      'upload',
      'share',
      'save',
      'print',
      'copy_all',
      'content_copy',
      'content_paste',
      'undo',
      'redo',
      'zoom_in',
      'zoom_out',
      'fullscreen',
      'fullscreen_exit',
      'visibility',
      'visibility_off',
      'lock',
      'lock_open',
      'key',
      'logout',
      'login',
      'power_settings_new',
      'restart_alt',
      'bolt',
    ],
  },
  {
    label: 'Komunikacja',
    icons: [
      'mail',
      'send',
      'chat',
      'chat_bubble',
      'forum',
      'call',
      'call_end',
      'phone',
      'sms',
      'notifications',
      'notifications_active',
      'notifications_off',
      'contact_mail',
      'contacts',
      'person',
      'group',
      'person_add',
      'alternate_email',
      'rss_feed',
      'video_call',
      'mic',
      'mic_off',
      'volume_up',
      'volume_off',
    ],
  },
  {
    label: 'Pliki i dane',
    icons: [
      'folder',
      'folder_open',
      'insert_drive_file',
      'description',
      'article',
      'attach_file',
      'link',
      'cloud',
      'cloud_upload',
      'cloud_download',
      'cloud_done',
      'storage',
      'database',
      'backup',
      'file_present',
      'picture_as_pdf',
      'table_chart',
      'bar_chart',
      'pie_chart',
      'analytics',
      'trending_up',
      'trending_down',
      'insights',
    ],
  },
  {
    label: 'Media',
    icons: [
      'image',
      'photo_camera',
      'videocam',
      'play_arrow',
      'pause',
      'stop',
      'skip_next',
      'skip_previous',
      'replay',
      'fast_forward',
      'fast_rewind',
      'movie',
      'music_note',
      'headphones',
      'photo_library',
      'collections',
      'crop',
      'filter',
      'brightness_6',
      'palette',
      'brush',
      'draw',
    ],
  },
  {
    label: 'Handel',
    icons: [
      'shopping_cart',
      'shopping_bag',
      'storefront',
      'add_shopping_cart',
      'local_offer',
      'sell',
      'payments',
      'credit_card',
      'account_balance',
      'account_balance_wallet',
      'receipt_long',
      'point_of_sale',
      'local_shipping',
      'inventory',
      'inventory_2',
      'redeem',
      'loyalty',
      /*
       * `percent`, not `discount`.
       *
       * `discount` is a real Material Symbols name on fonts.google.com but the
       * ligature is absent from the variable font the CSS2 endpoint serves for
       * all three styles - measured in the app, the glyph box came back 176 px
       * wide against 22 px for every neighbour here, which is the width of the
       * literal word "discount" rendered as text. That is exactly what the user
       * saw: one tile in this group showing its own name instead of an icon,
       * and the same word landing on their page after inserting it.
       */
      'percent',
    ],
  },
  {
    label: 'Czas i miejsce',
    icons: [
      'calendar_today',
      'event',
      'schedule',
      'alarm',
      'timer',
      'hourglass_empty',
      'today',
      'date_range',
      'place',
      'pin_drop',
      'flight',
      'directions_car',
      'directions_walk',
      'directions_bike',
      'train',
      'directions_bus',
      'hotel',
      'restaurant',
      'local_cafe',
    ],
  },
  {
    label: 'Informacje i alerty',
    icons: [
      'info',
      'help',
      'help_outline',
      'warning',
      'error',
      'report_problem',
      'priority_high',
      'star',
      'star_border',
      'star_half',
      'favorite',
      'favorite_border',
      'thumb_up',
      'thumb_down',
      'flag',
      'bookmark',
      'bookmark_border',
      'verified',
      'new_releases',
      'label',
    ],
  },
  {
    label: 'Dostępność',
    icons: [
      'accessible',
      'accessible_forward',
      'accessibility',
      'accessibility_new',
      'wheelchair_pickup',
      'hearing',
      'hearing_disabled',
      'closed_caption',
      'sign_language',
      'blind',
      'elderly',
      'visibility',
      'contrast',
    ],
  },
  {
    label: 'Urządzenia',
    icons: [
      'devices',
      'computer',
      'laptop',
      'smartphone',
      'tablet',
      'watch',
      'tv',
      'keyboard',
      'mouse',
      'wifi',
      'wifi_off',
      'bluetooth',
      'battery_full',
      'battery_charging_full',
      'signal_cellular_alt',
      'dark_mode',
      'light_mode',
    ],
  },
];

/** Every curated icon, flattened - for search across all groups at once. */
export const ALL_MATERIAL_SYMBOLS: string[] = MATERIAL_SYMBOL_GROUPS.flatMap((group) => group.icons);
